/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fis.poo.proyecto_cine.Vista;

import fis.poo.proyecto_cine.Controlador.Controlador;
import fis.poo.proyecto_cine.Vista.BoletoFactura;

/**
 *
 * @author sebas
 */
public class ContenedorPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContenedorPrincipal.class.getName());
    private final Controlador controlador1 = new Controlador();
    private MetodosAdministrador panelMetodosAdministrador;
    private EleccionPelicula panelEleccionPelicula;
    
    /**
     * Creates new form ContenedorPrincipal
     */
    
    public ContenedorPrincipal() {
        initComponents();
        
    contenedorPrincipal.setLayout(new java.awt.CardLayout());
    contenedorPrincipal.add(new PantallaSeleccionUsuario(this.controlador1), "ValidadorAdministrador");
    contenedorPrincipal.add(new ValidadorCliente(), "ValidadorCliente");
    contenedorPrincipal.add(new PantallaSeleccionUsuario(this.controlador1), "PantallaSeleccionUsuario");
    contenedorPrincipal.add(new ValidadorCliente(), "ValidadorCliente");
    contenedorPrincipal.add(new ValidadorAdministrador(), "ValidadorAdministrador");
    
    panelMetodosAdministrador = new MetodosAdministrador();
    contenedorPrincipal.add(panelMetodosAdministrador, "MetodosAdministrador");
    panelEleccionPelicula = new EleccionPelicula(this.controlador1);
    contenedorPrincipal.add(panelEleccionPelicula, "EleccionPelicula");
    
    //contenedorPrincipal.add(new MetodosAdministrador(), "MetodosAdministrador");
    //contenedorPrincipal.add(new EleccionPelicula(this.controlador1), "EleccionPelicula");
    contenedorPrincipal.add(new EleccionAsiento(this.controlador1), "EleccionAsiento");
    contenedorPrincipal.add(new BoletoFactura(), "BoletoFactura");






    
    //aqui muestro la priera pantalla
    java.awt.CardLayout cl = (java.awt.CardLayout) contenedorPrincipal.getLayout();
    cl.show(contenedorPrincipal, "PantallaSeleccionUsuario"); 
    
        
    }
    
    
    public Controlador getControlador(){
        return this.controlador1;
    }
    
    
    
    public void cambiarPanel(String nombrePanel) {
        if(nombrePanel.equals("MetodosAdministrador")){
            panelMetodosAdministrador.actualizarFunciones();
        }
        if(nombrePanel.equals("EleccionPelicula")){
        panelEleccionPelicula.actualizarFunciones();
        }
    java.awt.CardLayout cl = (java.awt.CardLayout) contenedorPrincipal.getLayout();
    cl.show(contenedorPrincipal, nombrePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 1000));
        setResizable(false);

        javax.swing.GroupLayout contenedorPrincipalLayout = new javax.swing.GroupLayout(contenedorPrincipal);
        contenedorPrincipal.setLayout(contenedorPrincipalLayout);
        contenedorPrincipalLayout.setHorizontalGroup(
            contenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        contenedorPrincipalLayout.setVerticalGroup(
            contenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(contenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ContenedorPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorPrincipal;
    // End of variables declaration//GEN-END:variables
}
